import { Image } from "expo-image";
import { useRouter } from "expo-router";
import { ArrowLeft, ShoppingBag, Trash2, X } from "lucide-react-native";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { assetUrl } from "@/config/environment";
import { clearCart, removeCart } from "@/api/client";
import { useAppStore } from "@/store/use-app-store";
import { colors, radius, type } from "@/theme/tokens";

export default function CartScreen() {
  const router = useRouter();
  const token = useAppStore((state) => state.accessToken);
  const cart = useAppStore((state) => state.cart);
  const refreshCart = useAppStore((state) => state.refreshCart);
  const setCart = useAppStore((state) => state.setCart);
  const total = cart.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0);

  const remove = async (id: string) => { try { await removeCart(token, id); await refreshCart(); } catch (error) { Alert.alert("移除失败", error instanceof Error ? error.message : "请稍后重试"); } };
  const empty = async () => { try { await clearCart(token); setCart([]); } catch (error) { Alert.alert("清空失败", error instanceof Error ? error.message : "请稍后重试"); } };

  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><View style={styles.header}><Pressable accessibilityLabel="关闭" onPress={() => router.back()} style={styles.close}><ArrowLeft size={19} color={colors.ink} /></Pressable><View><Text style={styles.eyebrow}>JAVA CART</Text><Text style={styles.title}>购物袋</Text></View>{cart.length > 0 && <Pressable accessibilityLabel="清空购物袋" onPress={() => void empty()} style={styles.clear}><Trash2 size={16} color={colors.error} /></Pressable>}</View>{!token ? <View style={styles.empty}><ShoppingBag size={27} color={colors.primary} /><Text style={styles.emptyTitle}>登录后使用购物袋</Text><Pressable style={styles.emptyButton} onPress={() => router.replace("/auth")}><Text style={styles.emptyButtonText}>去登录</Text></Pressable></View> : !cart.length ? <View style={styles.empty}><ShoppingBag size={27} color={colors.primary} /><Text style={styles.emptyTitle}>购物袋还是空的</Text><Text style={styles.emptyBody}>从发现页或 Agent 推荐中加入商品。</Text></View> : <><ScrollView contentContainerStyle={styles.items}>{cart.map((item) => <View key={item.id} style={styles.item}><Image source={{ uri: assetUrl(item.productImageUrl) }} style={styles.image} contentFit="cover" /><View style={styles.itemCopy}><Text style={styles.itemTitle} numberOfLines={2}>{item.productName}</Text><Text style={styles.itemPrice}>{item.unitPrice.toFixed(5)} × {item.quantity}</Text></View><Pressable accessibilityLabel={`移除 ${item.productName}`} onPress={() => void remove(item.id)} style={styles.remove}><X size={16} color={colors.error} /></Pressable></View>)}</ScrollView><View style={styles.checkout}><View><Text style={styles.totalLabel}>合计</Text><Text style={styles.totalValue}>{total.toFixed(5)}</Text></View><Pressable style={styles.checkoutButton}><Text style={styles.checkoutText}>去结算（{cart.length}）</Text></Pressable></View></>}</SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, header: { minHeight: 76, paddingHorizontal: 16, flexDirection: "row", gap: 13, alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.line }, close: { width: 39, height: 39, alignItems: "center", justifyContent: "center", borderRadius: 20, backgroundColor: colors.surface }, eyebrow: { color: colors.primary, fontFamily: type.mono, fontSize: 8, fontWeight: "800" }, title: { marginTop: 5, color: colors.ink, fontFamily: type.serif, fontSize: 25 }, clear: { marginLeft: "auto", width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: colors.errorSoft }, empty: { flex: 1, gap: 12, alignItems: "center", justifyContent: "center" }, emptyTitle: { color: colors.ink, fontSize: 15, fontWeight: "800" }, emptyBody: { color: colors.muted, fontSize: 10 }, emptyButton: { minHeight: 40, paddingHorizontal: 18, alignItems: "center", justifyContent: "center", borderRadius: 20, backgroundColor: colors.primary }, emptyButtonText: { color: colors.white, fontSize: 10, fontWeight: "800" }, items: { padding: 16, paddingBottom: 130 }, item: { paddingVertical: 8, flexDirection: "row", gap: 12, alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.line }, image: { width: 72, height: 82, borderRadius: radius.md, backgroundColor: colors.surfaceSoft }, itemCopy: { flex: 1 }, itemTitle: { color: colors.ink, fontSize: 13, fontWeight: "800" }, itemPrice: { marginTop: 5, color: colors.muted, fontFamily: type.mono, fontSize: 9 }, remove: { width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 17, backgroundColor: colors.errorSoft }, checkout: { position: "absolute", right: 0, bottom: 0, left: 0, minHeight: 92, padding: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: colors.line, backgroundColor: colors.surface }, totalLabel: { color: colors.muted, fontSize: 9 }, totalValue: { marginTop: 3, color: colors.ink, fontSize: 18, fontWeight: "800" }, checkoutButton: { minHeight: 46, paddingHorizontal: 20, alignItems: "center", justifyContent: "center", borderRadius: 23, backgroundColor: colors.primary }, checkoutText: { color: colors.white, fontSize: 11, fontWeight: "800" } });
